package org.ieszayas.practica24;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class InterfazMixta extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMixta
     */
    public InterfazMixta() {
        initComponents();
        inicializarEventosParte1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbOpcion1 = new javax.swing.JRadioButton();
        rbOpcion2 = new javax.swing.JRadioButton();
        rbOpcion3 = new javax.swing.JRadioButton();
        cbCheck1 = new javax.swing.JCheckBox();
        cbCheck2 = new javax.swing.JCheckBox();
        cbCheck3 = new javax.swing.JCheckBox();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtCampo1 = new javax.swing.JTextField();
        pwdContraseña = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnRedondo = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        cbLista = new javax.swing.JComboBox<>();
        spinner = new javax.swing.JSpinner();
        separator = new javax.swing.JSeparator();
        txtCorreoDup = new javax.swing.JTextField();
        txtCampo1Dup = new javax.swing.JTextField();
        pwdContraseñaDup = new javax.swing.JPasswordField();
        btnAceptarDup = new javax.swing.JButton();
        btnCancelarDup = new javax.swing.JButton();
        btnAyudaDup = new javax.swing.JButton();
        sliderDup = new javax.swing.JSlider();
        rbOpcion1Dup = new javax.swing.JRadioButton();
        rbOpcion2Dup = new javax.swing.JRadioButton();
        rbOpcion3Dup = new javax.swing.JRadioButton();
        cbCheck1Dup = new javax.swing.JCheckBox();
        cbCheck2Dup = new javax.swing.JCheckBox();
        cbCheck3Dup = new javax.swing.JCheckBox();
        lblCorreoDup = new javax.swing.JLabel();
        lblContraseñaDup = new javax.swing.JLabel();
        cbListaDup = new javax.swing.JComboBox<>();
        spinnerDup = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbOpcion1.setText("Opción 1");

        rbOpcion2.setText("Opción 2");

        rbOpcion3.setText("Opción 3");

        cbCheck1.setText("Opción 4");

        cbCheck2.setText("Opción 5");

        cbCheck3.setText("Opción 6");

        lblCorreo.setText("Correo");

        lblContraseña.setText("Contraseña");

        pwdContraseña.setText("....");

        btnAceptar.setText("Aceptar");

        btnRedondo.setText("Redondo");

        btnAyuda.setText("?");
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        cbLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCorreoDup.setEnabled(false);

        txtCampo1Dup.setEnabled(false);

        pwdContraseñaDup.setText("....");
        pwdContraseñaDup.setEnabled(false);

        btnAceptarDup.setText("Aceptar");
        btnAceptarDup.setEnabled(false);

        btnCancelarDup.setText("Redondo");
        btnCancelarDup.setEnabled(false);

        btnAyudaDup.setText("?");
        btnAyudaDup.setEnabled(false);
        btnAyudaDup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaDupActionPerformed(evt);
            }
        });

        sliderDup.setEnabled(false);

        rbOpcion1Dup.setText("Opción 1");
        rbOpcion1Dup.setEnabled(false);

        rbOpcion2Dup.setText("Opción 2");
        rbOpcion2Dup.setEnabled(false);

        rbOpcion3Dup.setText("Opción 3");
        rbOpcion3Dup.setEnabled(false);

        cbCheck1Dup.setText("Opción 4");
        cbCheck1Dup.setEnabled(false);

        cbCheck2Dup.setText("Opción 5");
        cbCheck2Dup.setEnabled(false);

        cbCheck3Dup.setText("Opción 6");
        cbCheck3Dup.setEnabled(false);

        lblCorreoDup.setText("Correo");
        lblCorreoDup.setEnabled(false);

        lblContraseñaDup.setText("Contraseña");
        lblContraseñaDup.setEnabled(false);

        cbListaDup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbListaDup.setEnabled(false);

        spinnerDup.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCorreo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContraseña)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCorreo)
                                .addGap(119, 119, 119)
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRedondo)
                                .addGap(18, 18, 18)
                                .addComponent(btnAyuda)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbOpcion1)
                        .addGap(18, 18, 18)
                        .addComponent(cbCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbOpcion3)
                                .addGap(18, 18, 18)
                                .addComponent(cbCheck3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbOpcion2)
                                .addGap(18, 18, 18)
                                .addComponent(cbCheck2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinner))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorreoDup)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContraseñaDup)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdContraseñaDup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCorreoDup)
                                        .addGap(119, 119, 119)
                                        .addComponent(btnAceptarDup)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelarDup)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAyudaDup)
                                        .addGap(19, 19, 19))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbOpcion1Dup)
                                .addGap(18, 18, 18)
                                .addComponent(cbCheck1Dup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCampo1Dup, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sliderDup, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbOpcion3Dup)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCheck3Dup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbOpcion2Dup)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCheck2Dup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbListaDup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerDup, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(separator))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion1)
                    .addComponent(cbCheck1)
                    .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion2)
                    .addComponent(cbCheck2)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion3)
                    .addComponent(cbCheck3)
                    .addComponent(cbLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(btnRedondo)
                    .addComponent(btnAyuda))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(pwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion1Dup)
                    .addComponent(cbCheck1Dup)
                    .addComponent(txtCampo1Dup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion2Dup)
                    .addComponent(cbCheck2Dup)
                    .addComponent(spinnerDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion3Dup)
                    .addComponent(cbCheck3Dup)
                    .addComponent(cbListaDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoDup)
                    .addComponent(txtCorreoDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarDup)
                    .addComponent(btnCancelarDup)
                    .addComponent(btnAyudaDup))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseñaDup)
                    .addComponent(pwdContraseñaDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnAyudaDupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaDupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaDupActionPerformed
    // METODOS
    private void inicializarEventosParte1() {
        // Campo 1: texto invertido
        txtCampo1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                actualizarCampo1();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                actualizarCampo1();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                actualizarCampo1();
            }

            private void actualizarCampo1() {
                String texto = txtCampo1.getText();
                txtCampo1Dup.setText(new StringBuilder(texto).reverse().toString());
            }
        });

        // Campo correo: igual
        txtCorreo.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                txtCorreoDup.setText(txtCorreo.getText());
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                txtCorreoDup.setText(txtCorreo.getText());
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                txtCorreoDup.setText(txtCorreo.getText());
            }
        });

        // Contraseña
        pwdContraseña.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                pwdContraseñaDup.setText(new String(pwdContraseña.getPassword()));
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                pwdContraseñaDup.setText(new String(pwdContraseña.getPassword()));
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                pwdContraseñaDup.setText(new String(pwdContraseña.getPassword()));
            }
        });

        // Radio Buttons
        javax.swing.ButtonGroup grupo1 = new javax.swing.ButtonGroup();
        grupo1.add(rbOpcion1);
        grupo1.add(rbOpcion2);
        grupo1.add(rbOpcion3);
        javax.swing.ButtonGroup grupo2 = new javax.swing.ButtonGroup();
        grupo2.add(rbOpcion1Dup);
        grupo2.add(rbOpcion2Dup);
        grupo2.add(rbOpcion3Dup);

        rbOpcion1.addActionListener(e -> rbOpcion1Dup.setSelected(true));
        rbOpcion2.addActionListener(e -> rbOpcion2Dup.setSelected(true));
        rbOpcion3.addActionListener(e -> rbOpcion3Dup.setSelected(true));

        // Checkboxes
        cbCheck1.addActionListener(e -> cbCheck1Dup.setSelected(cbCheck1.isSelected()));
        cbCheck2.addActionListener(e -> cbCheck2Dup.setSelected(cbCheck2.isSelected()));
        cbCheck3.addActionListener(e -> cbCheck3Dup.setSelected(cbCheck3.isSelected()));

        // ComboBox
        cbLista.addActionListener(e -> cbListaDup.setSelectedIndex(cbLista.getSelectedIndex()));

        // Spinner
        spinner.addChangeListener(e -> spinnerDup.setValue(spinner.getValue()));

        // Slider
        slider.addChangeListener(e -> sliderDup.setValue(slider.getValue()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMixta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarDup;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnAyudaDup;
    private javax.swing.JButton btnCancelarDup;
    private javax.swing.JButton btnRedondo;
    private javax.swing.JCheckBox cbCheck1;
    private javax.swing.JCheckBox cbCheck1Dup;
    private javax.swing.JCheckBox cbCheck2;
    private javax.swing.JCheckBox cbCheck2Dup;
    private javax.swing.JCheckBox cbCheck3;
    private javax.swing.JCheckBox cbCheck3Dup;
    private javax.swing.JComboBox<String> cbLista;
    private javax.swing.JComboBox<String> cbListaDup;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseñaDup;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoDup;
    private javax.swing.JPasswordField pwdContraseña;
    private javax.swing.JPasswordField pwdContraseñaDup;
    private javax.swing.JRadioButton rbOpcion1;
    private javax.swing.JRadioButton rbOpcion1Dup;
    private javax.swing.JRadioButton rbOpcion2;
    private javax.swing.JRadioButton rbOpcion2Dup;
    private javax.swing.JRadioButton rbOpcion3;
    private javax.swing.JRadioButton rbOpcion3Dup;
    private javax.swing.JSeparator separator;
    private javax.swing.JSlider slider;
    private javax.swing.JSlider sliderDup;
    private javax.swing.JSpinner spinner;
    private javax.swing.JSpinner spinnerDup;
    private javax.swing.JTextField txtCampo1;
    private javax.swing.JTextField txtCampo1Dup;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoDup;
    // End of variables declaration//GEN-END:variables
}
